### ISSUE TITLE
save updated source paths to project

### ISSUE THREAD

**Issue by JohannaOtt** [halestudio/hale#705] opened 2018-11-12 10:49 UTC
When opening a project using CSV-files with hale studio 3.4.1 and a resource's path has been changed, you can select a new path for the resource using the wizard that is showing up.
When saving the project afterwards the new path is saved to the halex-file.
This is the behaviour I would expect for all kinds of source schemas/data, because a change in a resource's path is probably persistent.

I tested the behaviour using fgdb and xml files, but for these cases, saving the project does not lead to updated paths in the halex file.

**Comment by florianesser** [comment] 2018-11-29 16:59
Duplicate of #641

**Closed by florianesser** 2018-11-29 16:59 UTC
Labels: duplicate
