### ISSUE TITLE
support for single datasources the actions: remove and update

### ISSUE THREAD

**Issue by doemming** [halestudio/hale#501] opened 2018-02-01 15:44 UTC
when working with multiple data sources in one project it would be great if the user could update or clear single data sources. Currently the action "clear" is always applied to all data sources.

**Comment by thorsten-reitz** [comment] 2018-02-03 07:05
Please note this is a duplicate of https://github.com/halestudio/hale/issues/131 - I will thus close this one.
And yes, I'd also love to have this feature :).

**Closed by thorsten-reitz** 2018-02-03 07:05 UTC
Labels: feature
