### ISSUE TITLE
Using Export-->hale connect project... corrupts paths to resources in .halex

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [halestudio/hale#746] opened 2019-06-19 07:17 UTC
I created several transformation projects for MST Denmark this past week. For each transformation project, I exported it directly to hale connect using the option:
File --> Export --> hale connect project...
After exporting the projects, the paths to the source data are altered and contain what looks like a relative path beginning with 'resource1':
<setting name="source">resource1/RiverBasinDistrict.shp</setting>
You can view the affected transformation projects here on Box: https://wetransform.box.com/s/guapspufeho7y4of5zxdlttrxg5wy9g6

**Comment by thorsten-reitz** [comment] 2021-07-29 15:43
@florianesser @Kate-Lyndegaard Is this really a bug? IIRC that is the bundle/archive path inside the archive that was uploaded. I wouldn't expect or want to see my local paths being exposed after upload.

**Comment by Kate-Lyndegaard** [comment] 2021-07-30 07:02
@thorsten-reitz I think the issue here, was that the .halex files stored locally were altered. The uploaded transformation projects on haleconnect contain the bundle/archive paths, and that is expected. What was not expected, was that the local paths of the .halex files stored locally would be altered. 

Using the latest version of hale studio (4.1.0), I cannot reproduce the issue.

**Comment by thorsten-reitz** [comment] 2021-07-30 07:04
@Kate-Lyndegaard OK thanks for the clarification. If it can't reproduce anymore, I'd vote in favour of closing the issue.

**Closed** 2021-07-30 07:33 UTC
Labels: bug, io
